site_name: Nelofus's perch
site_url: https://nelofus2007.github.io/
theme:
  name: material
  font: false

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Diary: 
    - Diary/index.md
    - "2026年":
      - "6月":
        - "27日": Diary/2026/06/Day27.md

plugins:
  - search
  - encryptcontent:
        title_prefix: '[LOCKED]'

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to Dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to Light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

