site_name: Nelofus's Note
site_url: https://nelofus2007.github.io/

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - "EnumerativeComb":
    - EnumC/index.md
    - ElementaryTech:
      - GeneratingFunction:
        - EnumC/ElementaryTech/GeneratingFunction/GF-1_Basic.md
  - Math:
    - Math/index.md
    - Tier1:
      - MA / 数学分析:
        - 1-Fundamental:
          - 1.1 极限: Math/Tier1/MA/1-Fundamental/1-1_Limit.md
      - AlgF / 代数学基础:
        - 概述: Math/Tier1/AlgF/Overview.md
        - 1-PreKnowledge:
          - 1.1 何谓代数: Math/Tier1/AlgF/1-PreKnowledge/1-1_Algebra.md
  - Diary:
    - Diary/index.md
    - "2026年":
      - "6月":
        - "27日": Diary/2026/06/Day27.md

plugins:
  - search
  - encryptcontent:
      title_prefix: '[LOCKED]'
  - theorem_envs:
      left_rule: 2px
      right_rule: 1px
      top_rule: 0px
      bottom_rule: 0px
  - typst_ts:
      width_step: 1

theme:
  name: material
  font: false
  language: zh
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to Dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to Light mode

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
